-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Dec 17, 2025 at 05:43 AM
-- Server version: 9.1.0
-- PHP Version: 8.3.14

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `pikaa`
--

-- --------------------------------------------------------

--
-- Table structure for table `song`
--

DROP TABLE IF EXISTS `song`;
CREATE TABLE IF NOT EXISTS `song` (
  `SONG_ID` int UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'The id of the song.',
  `SONG_TITLE` text NOT NULL COMMENT 'The title of the song.',
  `SONG_GENRE` text NOT NULL COMMENT 'The genre(s) of the song.',
  `SONG_ARTIST` text NOT NULL COMMENT 'The artist of the song.',
  `SONG_RELEASE_YEAR` int UNSIGNED NOT NULL COMMENT 'Which year the song was released.',
  `SONG_LYRICS` longtext NOT NULL COMMENT 'The lyrics of the song.',
  `SONG_COVER_URL` text NOT NULL COMMENT 'The link to the song cover image.',
  `SONG_VIDEO_URL` text NOT NULL COMMENT 'The link to the song music video.',
  `SONG_MUSICS_URL` text NOT NULL COMMENT 'The link to the song music sound.',
  PRIMARY KEY (`SONG_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=27 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='The information about each song';

--
-- Dumping data for table `song`
--

INSERT INTO `song` (`SONG_ID`, `SONG_TITLE`, `SONG_GENRE`, `SONG_ARTIST`, `SONG_RELEASE_YEAR`, `SONG_LYRICS`, `SONG_COVER_URL`, `SONG_VIDEO_URL`, `SONG_MUSICS_URL`) VALUES
(4, 'Never Gonna Give You Up', 'Dance-Pop', 'Rick Astley', 1897, 'We\'re no strangers to love\r\nYou know the rules and so do I\r\nA full commitment\'s what I\'m thinking of\r\nYou wouldn\'t get this from any other guy\r\n\r\nI just wanna tell you how I\'m feeling\r\nGotta make you understand\r\n\r\nNever gonna give you up\r\nNever gonna let you down\r\nNever gonna run around and desert you\r\nNever gonna make you cry\r\nNever gonna say goodbye\r\nNever gonna tell a lie and hurt you\r\n\r\nWe\'ve known each other for so long\r\nYour heart\'s been aching, but you\'re too shy to say it\r\nInside, we both know what\'s been going on\r\nWe know the game and we\'re gonna play it\r\n\r\nAnd if you ask me how I\'m feeling\r\nDon\'t tell me you\'re too blind to see\r\n\r\nNever gonna give you up\r\nNever gonna let you down\r\nNever gonna run around and desert you\r\nNever gonna make you cry\r\nNever gonna say goodbye\r\nNever gonna tell a lie and hurt you\r\n\r\nNever gonna give you up\r\nNever gonna let you down\r\nNever gonna run around and desert you\r\nNever gonna make you cry\r\nNever gonna say goodbye\r\nNever gonna tell a lie and hurt you\r\n\r\n(Ooh, give you up)\r\n(Ooh, give you up)\r\nNever gonna give, never gonna give\r\n(Give you up)\r\nNever gonna give, never gonna give\r\n(Give you up)\r\n\r\nWe\'ve known each other for so long\r\nYour heart\'s been aching, but you\'re too shy to say it\r\nInside, we both know what\'s been going on\r\nWe know the game and we\'re gonna play it\r\n\r\nI just wanna tell you how I\'m feeling\r\nGotta make you understand\r\n\r\nNever gonna give you up\r\nNever gonna let you down\r\nNever gonna run around and desert you\r\nNever gonna make you cry\r\nNever gonna say goodbye\r\nNever gonna tell a lie and hurt you\r\n\r\nNever gonna give you up\r\nNever gonna let you down\r\nNever gonna run around and desert you\r\nNever gonna make you cry\r\nNever gonna say goodbye\r\nNever gonna tell a lie and hurt you\r\n\r\nNever gonna give you up\r\nNever gonna let you down\r\nNever gonna run around and desert you\r\nNever gonna make you cry\r\nNever gonna say goodbye\r\nNever gonna tell a lie and hurt you', 'https://images.genius.com/0a468b8c54bc6f751ba47c74bc409869.1000x1000x1.jpg', 'https://www.youtube.com/embed/dQw4w9WgXcQ', 'https://open.spotify.com/embed/track/4uLU6hMCjMI75M1A2tKUQC?utm_source=generator&theme=0'),
(7, 'ANIMA', 'Anime, J-Pop', 'ReoNa', 2020, '魂の色は 何色ですか\r\n\r\n「もういっそ 折れたままで」\r\n捨てるほど 逃げ出すほど\r\n強くないよ ほら\r\nもう一度 鼓動、高鳴る\r\n何が正しいかなんて\r\nわからないけど\r\n\r\n形のないものばかりが\r\n大切になって行く (something to live)\r\n飾らない言葉だけが\r\n強く結ばれてる (forgive the soul)\r\n\r\nまた 躓いて 転がって\r\nそれでも砕けない\r\n魂の色は 何色ですか\r\nただ 傷ついて 強がって\r\nそれでも見つけたいよ\r\n魂のカタチ 確かめてるよ\r\n\r\n深い地の底で一人\r\n扉と鍵を探す\r\nおとぎ話は ほら\r\n泡の様に全部消えて\r\n葛藤、残像だけ\r\n次の 頁へ\r\n\r\n伸びてく枝葉が分かれて\r\nそれぞれの道を行く (something to live)\r\n寂しい思い出だけが\r\n強く根を張ってる (killing am I)\r\n\r\nまだ 貫いて 失って\r\nそれでも挫けない\r\n心はどこに 器はどこに\r\nただ 残されて 抜け落ちて\r\nそれでも伝えたいよ\r\n魂の日々を 魂の意志を\r\nずっと wow, wow, wow\r\nずっと wow, wow, wow\r\n\r\n（魂の色は 何色ですか）\r\n（赤色ですか 青色ですか）\r\n魂の色は （魂の色は）\r\n何色ですか （何色ですか）\r\n透明な過去に 不透明な明日に\r\n生きるあなたは 何色ですか\r\n\r\nまた 躓いて 転がって\r\nそれでも砕けない\r\n魂の色は 何色ですか\r\nただ 傷ついて 強がって\r\nそれでも見つけたいよ\r\n魂のカタチ 確かめてるよ\r\n\r\nずっと wow, wow, wow\r\nずっと wow, wow, wow\r\nずっと wow, wow, wow (something to live)\r\nずっとwow, wow, wow (something to live)', 'https://images.genius.com/845aecd3d006260fbd8777976043fa20.1000x1000x1.jpg', 'https://youtube.com/embed/Qo_4XqKwrSM?si=fXUUNXpjYfc-x5mN', 'https://open.spotify.com/embed/track/2j1r3ubqqxuoTFaPVnTV1j?utm_source=generator&theme=0'),
(9, 'Bohemian Rhapsody', 'Rock', 'Queen', 1975, 'Is this the real life? Is this just fantasy?\r\nCaught in a landslide, no escape from reality\r\nOpen your eyes, look up to the skies and see\r\nI\'m just a poor boy (ooh, poor boy), I need no sympathy\r\nBecause I\'m easy come, easy go, little high, little low\r\nAny way the wind blows doesn\'t really matter to me, to me\r\n\r\nMama, just killed a man\r\nPut a gun against his head, pulled my trigger, now he\'s dead\r\nMama, life had just begun\r\nBut now I\'ve gone and thrown it all away\r\nMama, ooh, didn\'t mean to make you cry\r\nIf I\'m not back again this time tomorrow\r\nCarry on, carry on as if nothing really matters\r\n\r\nToo late, my time has come\r\nSends shivers down my spine, body\'s aching all the time\r\nGoodbye everybody, I\'ve got to go\r\nGotta leave you all behind, and face the truth\r\nMama, ooh (any way the wind blows)\r\nI don\'t wanna die\r\nI sometimes wish I\'d never been born at all\r\n\r\nI see a little silhouetto of a man\r\nScaramouche, Scaramouche, will you do the Fandango?\r\nThunderbolt and lightning, very, very frightening me\r\n(Galileo) Galileo (Galileo), Galileo, Galileo Figaro, magnifico\r\nI\'m just a poor boy, nobody loves me\r\n(He\'s just a poor boy from a poor family)\r\n(Spare him his life from this monstrosity)\r\n\r\nEasy come, easy go, will you let me go?\r\nBismillah! No, we will not let you go (let him go)\r\nBismillah! We will not let you go (let him go)\r\nBismillah! We will not let you go (let me go)\r\nWill not let you go (let me go)\r\nWill not let you go, never (let me go)\r\n\r\nNo, no, no, no, no, no, no\r\nOh, mamma mia, mamma mia\r\nMamma mia, let me go\r\n\r\nBeelzebub has a devil put aside for me, for me, for me\r\nSo you think you can stone me and spit in my eye?\r\nSo you think you can love me and leave me to die?\r\nOh, baby, can\'t do this to me, baby\r\nJust gotta get out, just gotta get right outta here\r\n\r\nOoh\r\nOoh, yeah, ooh, yeah\r\n\r\nNothing really matters, anyone can see\r\nNothing really matters\r\nNothing really matters to me\r\n\r\nAny way the wind blows', 'https://powerpop.blog/wp-content/uploads/2020/08/queen-bohemian-rhapsody.jpg', 'https://youtube.com/embed/fJ9rUzIMcZQ?list=RDfJ9rUzIMcZQ', 'https://open.spotify.com/embed/track/3z8h0TU7ReDPLIbEnYhWZb?utm_source=generator&theme=0'),
(10, 'Beneath The Mask', 'Acid-Jazz, Jazz-Fusion', 'Lyn Inaizumi', 2017, 'Where have you been? Been searching all along\r\nCame facing twilight, on and on, without a clue\r\nWithout a sign, without grasping, yet\r\nThe real question to be asked, where have I been?\r\n\r\nI\'m a shapeshifter at Poe\'s masquerade\r\nHiding both face and mind, all free for you to draw\r\nI\'m a shapeshifter, what else should I be?\r\nPlease don\'t take off my mask, revealing dark\r\n\r\nMoments of calm, nothing left to be found\r\nA mirror right in front of me, that\'s where I find\r\nAn empty glass, reflecting the sad truth\r\nIt\'s telling words not to be told, I need the mask\r\n\r\nI\'m a shapeshifter at Poe\'s masquerade\r\nHiding both face and mind, all free for you to draw\r\nI\'m a shapeshifter, chained down to my core\r\nPlease don\'t take off my mask, my place to hide\r\n\r\nI can\'t tell you how to see me\r\nJust a cage of bones, there\'s nothing inside\r\nWill it unleash me, burning down the walls?\r\nIs there a way for me to break?\r\n\r\nI\'m a shapeshifter at Poe\'s masquerade\r\nHiding both face and mind, all free for you to draw\r\nI\'m a shapeshifter have no face to show\r\nPlease don\'t take off my mask, my disguise', 'https://i.scdn.co/image/ab67616d0000b2732a061f8cc383443cbb46adf6', 'https://youtube.com/embed/U2Qd9TRY1Ro?si=VzAJEEUcNc8j23tX', 'https://open.spotify.com/embed/track/5XLXrm5JVMdOus1fWmTOFw?utm_source=generator&theme=0'),
(11, 'Black Star', 'Rock, Indie-Rock', 'Radiohead', 1995, 'I get home from work\r\nAnd you\'re still standing in your dressing gown\r\nWell, what am I to do?\r\nI know all the things around your head\r\nAnd what they do to you\r\n\r\nWhat are we coming to?\r\nWhat are we gonna do?\r\n\r\nBlame it on the black star\r\nBlame it on the falling sky\r\nBlame it on the satellite\r\nThat beams me home\r\n\r\nTroubled words of a troubled mind\r\nI try to understand what is eating you\r\nI try to stay awake, but it\'s 58 hours\r\nSince that I last slept with you\r\n\r\nWhat are we coming to?\r\nI just don\'t know anymore\r\n\r\nBlame it on the black star\r\nBlame it on the falling sky\r\nBlame it on the satellite\r\nThat beams me home\r\n\r\nI get on the train and I just stand about\r\nNow that I don\'t think of you\r\nI keep falling over, I keep passing out\r\nWhen I see a face like you\r\n\r\nWhat am I coming to?\r\nI\'m gonna melt down\r\n\r\nBlame it on the black star\r\nBlame it on the falling sky\r\nBlame it on the satellite\r\nThat beams me home\r\n\r\nThis is killing me\r\nThis is killing me', 'https://images.genius.com/251c0ecbd0bee2c27edc46c5d10342cd.1000x1000x1.png', 'https://youtube.com/embed/d7lbzUUXj0k?si=UQgwC0JvJxxwZ3WM', 'https://open.spotify.com/embed/track/6UO72VSXEONxdfLyABihs9?utm_source=generator&theme=0'),
(12, 'Dealova', 'Pop, Rock', 'Once Mekel', 2012, 'Aku ingin menjadi\r\nMimpi indah dalam tidurmu\r\nAku ingin menjadi sesuatu\r\nYang mungkin bisa kau rindu\r\nKarena langkah merapuh tanpa dirimu\r\nOh, karena hati t\'lah letih\r\n\r\nAku ingin menjadi sesuatu\r\nYang s\'lalu bisa kau sentuh\r\nAku ingin kau tahu\r\nBahwa ku selalu memujamu\r\nTanpamu, sepinya waktu merantai hati\r\nOh, bayangmu seakan-akan\r\n\r\nKau seperti nyanyian dalam hatiku\r\nYang memanggil rinduku padamu, oh\r\nSeperti udara yang kuhela\r\nKau selalu ada\r\n\r\nOh-uh-uh, oh-ho-uh-uh\r\nOh-uh-uh, oh-oh-oh\r\n\r\nHanya dirimu yang bisa membuatku tenang\r\nTanpa dirimu aku merasa hilang\r\nDan sepi\r\nDan sepi\r\n\r\nKau seperti nyanyian dalam hatiku\r\nYang memanggil rinduku padamu, oh\r\nSeperti udara yang kuhela\r\nKau selalu ada\r\n\r\nKau seperti nyanyian dalam hatiku\r\nYang memanggil rinduku padamu, oh\r\nSeperti udara yang kuhela\r\nKau selalu ada\r\n\r\nSelalu ada\r\nKau selalu ada\r\nSelalu ada\r\nKau selalu ada\r\n\r\nSya-na-na-na-na, na-na-na-oh-oh\r\nSya-na-na-na-na, na-na-na-oh-oh\r\nSya-na-na-na-na, na-na-na-oh-oh\r\nSelalu ada', 'https://i.scdn.co/image/ab67616d0000b273bbf16732627e8276f755a33e', 'https://youtube.com/embed/TgkCr0BgdIs?list=RDTgkCr0BgdIs', 'https://open.spotify.com/embed/track/4Eybcl06frChLYoXm0sxJi?utm_source=generator&theme=0'),
(13, 'Everlong', 'Hard-Rock, Punk, Post-Grunge', 'Foo Fighter', 1997, 'Hello\r\nI\'ve waited here for you\r\nEverlong\r\n\r\nTonight, I throw myself into\r\nAnd out of the red\r\nOut of her head, she sang\r\n\r\nCome down and waste away with me\r\nDown with me\r\nSlow, how you wanted it to be\r\nI\'m over my head\r\nOut of her head, she sang\r\n\r\nAnd I wonder\r\nWhen I sing along with you\r\n\r\nIf everything could ever be this real forever\r\nIf anything could ever be this good again\r\nThe only thing I\'ll ever ask of you\r\nYou\'ve got to promise not to stop when I say when\r\nShe sang\r\n\r\nBreathe out\r\nSo I can breathe you in\r\nHold you in\r\nAnd now\r\nI know you\'ve always been\r\nOut of your head\r\nOut of my head, I sang\r\n\r\nAnd I wonder\r\nWhen I sing along with you\r\n\r\nIf everything could ever feel this real forever\r\nIf anything could ever be this good again\r\nThe only thing I\'ll ever ask of you\r\nYou\'ve got to promise not to stop when I say when\r\nShe sang\r\n\r\nAnd I wonder\r\n\r\nIf everything could ever feel this real forever\r\nIf anything could ever be this good again\r\nThe only thing I\'ll ever ask of you\r\nYou\'ve got to promise not to stop when I say when', 'https://upload.wikimedia.org/wikipedia/en/4/45/Everlong_by_Foo_Fighters_standard_artwork.png', 'https://youtube.com/embed/eBG7P-K-r1Y?si=sTQ8UMXuVZwKXxTA', 'https://open.spotify.com/embed/track/5UWwZ5lm5PKu6eKsHAGxOk?utm_source=generator&theme=0'),
(15, 'Eien No Akuruhi', 'Pop, J-Pop', 'Ado', 2022, '恋をしてしまった 涙の痕\r\n洗う雨は虹の予告編だ\r\nなぜ君がここにいないんだろう\r\n\"世界一有名な言葉\" 強がって恨んでみたり\r\n\r\nLa la la love\r\nLa la la love\r\n\r\nまるで映画のエンドロールだ\r\nOh あいしてる あいしてる あいしてるなんて\r\n「さよなら」みたいに云わないでよね\r\nもうあいしてる あいしてる あいしてるなんていらない\r\n\r\n「今 時間を止めたね 1秒くらい」\r\n見惚れていたなんて云えなかったよ\r\n君だけがいなくて 永遠のあくる日みたい\r\n神様それはあんまりじゃないか\r\n\r\nまるでベタな映画のエンドロールだ\r\nOh あいしてる あいしてる あいしてるなんて\r\n正しいことばっか云わないでくれ\r\nもうあいしてる あいしてる あいしてるなんて\r\n\r\n聞き飽きたでしょう? ありふれた言葉\r\nそれでもロックバンドもアイドル歌手も\r\n「あいしてる」「あいしてる」だったんだ\r\n\r\nどうして云わずにいられないんだろう (醜い)\r\n(あいしてる あいしてる あいしてる)\r\nおんなじ言葉繰り返している (ラブソング)\r\n(あいしてる あいしてる あいしてる) あいしてる\r\n\r\nまるで映画のエンドロールだったな\r\n最後の君の笑顔は\r\nそれでもぼくらはあいしてる あいしてる あいしてる umm\r\n懲りずに飽きずに\r\nLove, love, love, love, love, love\r\nあいしてる', 'https://images.genius.com/eaabd0f817a4726c480a5e0f8f615e97.1000x1000x1.png', 'https://youtube.com/embed/ZHAnZTVF_10?si=jKCMWf30UziijlCt', 'https://open.spotify.com/embed/track/3cpKdrgCGfWVTzsf6o9JSK?utm_source=generator&theme=0'),
(17, 'Enchanted', 'Country-Pop, Power-Pop', 'Taylor Swift', 2010, 'There I was again tonight\r\nForcing laughter, faking smiles\r\nSame old tired, lonely place\r\nWalls of insincerity, shifting eyes and vacancy\r\nVanished when I saw your face\r\nAll I can say is, it was enchanting to meet you\r\n\r\nYour eyes whispered, \"Have we met?\"\r\n\'Cross the room your silhouette\r\nStarts to make its way to me\r\nThe playful conversation starts\r\nCounter all your quick remarks\r\nLike passing notes in secrecy\r\n\r\nAnd it was enchanting to meet you\r\nAll I can say is, I was enchanted to meet you\r\n\r\nThis night is sparkling, don\'t you let it go\r\nI\'m wonderstruck, blushing all the way home\r\nI\'ll spend forever wondering if you knew\r\nI was enchanted to meet you\r\n\r\nThe lingering question kept me up\r\n2 AM, who do you love?\r\nI wonder \'til I\'m wide awake\r\nAnd now I\'m pacing back and forth\r\nWishing you were at my door\r\nI\'d open up and you would say, \"Hey\"\r\n\r\nIt was enchanting to meet you\r\nAll I know is, I was enchanted to meet you\r\n\r\nThis night is sparkling, don\'t you let it go\r\nI\'m wonderstruck, blushing all the way home\r\nI\'ll spend forever wondering if you knew\r\nThat this night is flawless, don\'t you let it go\r\nI\'m wonderstruck, dancing around all alone\r\nI\'ll spend forever wondering if you knew\r\nI was enchanted to meet you\r\n\r\nThis is me praying that\r\nThis was the very first page\r\nNot where the story line ends\r\nMy thoughts will echo your name, until I see you again\r\nThese are the words I held back, as I was leaving too soon\r\nI was enchanted to meet you\r\nPlease don\'t be in love with someone else\r\nPlease don\'t have somebody waiting on you\r\nPlease don\'t be in love with someone else\r\nPlease don\'t have somebody waiting on you\r\n\r\nThis night is sparkling, don\'t you let it go\r\nI\'m wonderstruck, blushing all the way home\r\nI\'ll spend forever wondering if you knew\r\nThis night is flawless, don\'t you let it go\r\nI\'m wonderstruck, dancing around all alone\r\nI\'ll spend forever wondering if you knew\r\nI was enchanted to meet you\r\n\r\nPlease don\'t be in love with someone else\r\nPlease don\'t have somebody waiting on you', 'https://images.genius.com/cb5181bd9514789f58ac3abf67e69144.1000x1000x1.jpg', 'https://youtube.com/embed/vv3um0BlygY?si=WUCdouZq_epi1flZ', 'https://open.spotify.com/embed/track/04S1pkp1VaIqjg8zZqknR5?utm_source=generator&theme=0'),
(18, 'Fly Me To The Moon', 'Jazz, Pop, Swing', 'Count Basie and Frank Sinatra', 1965, 'Fly me to the moon\r\nLet me play among the stars\r\nLet me see what spring is like\r\nOn a-Jupiter and Mars\r\n\r\nIn other words: hold my hand\r\nIn other words: baby, kiss me\r\n\r\nFill my heart with song\r\nAnd let me sing for ever more\r\nYou are all I long for\r\nAll I worship and adore\r\n\r\nIn other words: please, be true\r\nIn other words: I love you\r\n\r\nFill my heart with song\r\nLet me sing for ever more\r\nYou are all I long for\r\nAll I worship and adore\r\n\r\nIn other words: please, be true\r\nIn other words, in other words: I love you', 'https://images.genius.com/2eca85ad8e208ea2dc52e02d98b521f5.500x500x1.jpg', 'https://youtube.com/embed/JYuyWrkwpok?si=G6-YFWs3WAnm-3cI', 'https://open.spotify.com/embed/track/7FXj7Qg3YorUxdrzvrcY25?utm_source=generator&theme=0'),
(19, 'From The Start', 'Bossa-Nova, Jazz, Pop', 'Laufey', 2023, 'Don\'t you notice how\r\nI get quiet when there\'s no one else around?\r\nMe and you and awkward silence\r\nDon\'t you dare look at me that way\r\nI don\'t need reminders of how you don\'t feel the same\r\n\r\nOh, the burning pain\r\nListening to you harp on \'bout some new soulmate\r\n\"She\'s so perfect, \" blah, blah, blah\r\nOh, how I wish you\'ll wake up one day\r\nRun to me, confess your love, at least just let me say\r\n\r\nThat when I talk to you, oh, Cupid walks right through\r\nAnd shoots an arrow through my heart\r\nAnd I sound like a loon, but don\'t you feel it too?\r\nConfess I loved you from the start\r\n\r\nWhat\'s a girl to do?\r\nLying on my bed, staring into the blue\r\nUnrequited, terrifying\r\nLove is driving me a bit insane\r\nHave to get this off my chest\r\nI\'m telling you today\r\n\r\nThat when I talk to you, oh, Cupid walks right through\r\nAnd shoots an arrow through my heart\r\nAnd I sound like a loon, but don\'t you feel it too?\r\nConfess I loved you from the start\r\n\r\nConfess I loved you\r\nJust thinking of you\r\nI know I\'ve loved you from the start', 'https://upload.wikimedia.org/wikipedia/en/0/0e/Laufey_-_From_the_Start.png', 'https://youtube.com/embed/lSD_L-xic9o?si=xcfmCqWYvyoQRTqR', 'https://open.spotify.com/embed/track/43iIQbw5hx986dUEZbr3eN?utm_source=generator&theme=0'),
(20, 'Fine', 'K-Pop', 'Taeyeon', 2017, '찢어진 종잇조각에 담아낸 나의 진심에\r\n선명해져 somethin\' \'bout you (\'bout you)\r\nYeah, 나를 많이 닮은 듯 다른\r\n넌 혹시 나와 같을까? 지금 괜한 기대를 해 (해)\r\n\r\n하루 한 달 일 년쯤 되면\r\n서로 다른 일상을 살아가?\r\n\r\n나는 아니야, 쉽지 않을 것 같아, 야\r\n여전하게도 넌 내 하루하루를 채우고\r\n아직은 아니야, 바보처럼 되뇌는 나\r\n입가에 맴도는 말을 삼킬 수 없어\r\n\r\nIt\'s not fine\r\nAh-ah-ah, yeah\r\nAh-ah-ah, fine\r\nIt\'s not fine\r\n\r\n머릴 질끈 묶은 채 어지러운 방을 정리해\r\n찾고 있어 somethin\' new (somethin\' new)\r\n가끔 이렇게 감당할 수 없는\r\n뭐라도 해야 할 것만 같은 기분에 괜히 움직이곤 해 (해)\r\n\r\n하루 한 달 일 년 그쯤이면\r\n웃으며 추억할 거라 했지만\r\n\r\n나는 아니야, 쉽지 않을 것 같아, 야\r\n여전하게도 넌 내 하루하루를 채우고\r\n아직은 아니야, 바보처럼 되뇌는 나\r\n입가에 맴도는 말을 삼킬 수 없어\r\n\r\nIt\'s not fine (it\'s not fine)\r\nAh-ah-ah, yeah (it\'s not fine)\r\nAh-ah-ah, fine (oh-whoa, oh)\r\nIt\'s not fine\r\n\r\n의미 없는 농담, 주고받는 대화\r\n사람들 틈에 난 아무렇지 않아 보여\r\n무딘 척 웃음을 지어 보이며\r\n너란 그늘을 애써 외면해보지만\r\n\r\n우리 마지막 그 순간이 자꾸 떠올라\r\n잘 지내란 말이 전부였던 담담한 이별 (oh)\r\n아직은 아니야, 바보처럼 되뇌는 그 말 (되뇌는 그 말)\r\n입가에 맴도는 말을 삼킬 수 없어\r\n\r\nIt\'s not fine (ah, yeah)\r\nAh-ah-ah, yeah (ah, yeah)\r\nAh-ah-ah, fine (ah, yeah)\r\n(It\'s not fine) it\'s not fine (oh, whoa)\r\n\r\nOh-oh-oh (oh, whoa)\r\nOh-oh-oh, yeah (oh, ooh)\r\nOh-oh-oh, fine\r\nIt\'s not fine', 'https://images.genius.com/23d79050b4e96b5b1f004a4b3b3461be.1000x1000x1.jpg', 'https://youtube.com/embed/NHXUM-6a3dU?si=mDDc34gM_pylovp_', 'https://open.spotify.com/embed/track/6CdUgvL597jWmW4w8P5kHs?utm_source=generator&theme=0'),
(21, 'Forever Young', 'K-Pop', 'Blackpink', 2018, '떠나지 마 Just stay\r\n지금 이 시간을 멈춘 채\r\n너와 함께라면 난\r\nI could die in this moment\r\nForever young\r\nForever young\r\nForever young\r\nForever young\r\n\r\n너의 눈에 비친 나의 모습이\r\n늘 처음 만난 그 날만 같길\r\n소리 없이 타오르는 불꽃같이\r\n마지막처럼 내 입맞추길\r\n\r\n달빛 아래 내 마음은 설레\r\n은하수로 춤추러 갈래 Let’s go\r\n지금 Let go\r\n오늘이 가도 후회 없게\r\n시간이 우리 둘을 떼어 놓을 수 없게\r\n순간이 영원할 수 있게\r\n\r\n넌 내 마음에 불을 질러줘\r\n후회 없는 젊음이 타오르게\r\n지금처럼 너와 함께라면 Tonight\r\nI could die in this moment\r\n\r\nForever young\r\nForever young\r\nForever young\r\nForever young\r\n\r\n매일매일 밤 밤\r\n이 노래를 불러 불러\r\nKnow we got that bomb bomb\r\nCome again come again\r\n\r\nForever young boy so we ride or die\r\n끝이 없을 것처럼 달려 너와 나\r\n붉은 Sunset 아래 너는 지금 내 옆에\r\nPinked out or murdered out like it ain’t no thing\r\n다 필요 없어 주인공은 우리\r\nSay life’s a bitch? But mine’s a movie\r\n내 Diamond처럼 We’ll shine together\r\nWhenever wherever forever ever ever\r\n\r\n짜릿하게 더 위험하게\r\n세상 저 끝까지 가볼래 Let’s go\r\n지금 Let go\r\n오늘이 가도 후회 없게\r\n시간이 우리 둘을 떼어 놓을 수 없게\r\n순간이 영원할 수 있게\r\n\r\n넌 내 마음에 불을 질러줘\r\n후회 없는 젊음이 타오르게\r\n세상 무엇도 두렵지 않아 Tonight\r\nI could die in this moment\r\n\r\nForever young\r\n\r\n달이 뜨고 별이 뜨면 춤추는 Body\r\n끝이 없이 달려보자 We like to party\r\n달이 뜨고 별이 뜨면 춤추는 Body\r\n끝이 없이 달려보자 We like to party\r\n\r\nGirls wanna have some fun\r\nWe go dumb dumb dumb\r\nGirls wanna have some fun\r\nWhat you want want want\r\n\r\nGirls wanna have some fun\r\nWe go dumb dumb dumb\r\nGirls wanna have some fun\r\nWe ain’t done done done\r\n\r\nWhatta bum bum whatta bum bum\r\nWhatta bum bum whatta bum bum\r\nWhatta bum bum whatta bum bum\r\nWhatta bum bum whatta bum bum\r\n\r\nWhatta bum bum whatta bum bum\r\nWhatta bum bum whatta bum bum\r\nWhatta bum bum whatta bum bum\r\nWhatta bum bum whatta bum bum', 'https://images.genius.com/432454520f7aaed47ff842ecb15d649e.886x886x1.jpg', 'https://youtube.com/embed/-gibBYpzZbI?si=j5YOFXg6rPruUzNB', 'https://open.spotify.com/embed/track/2Pp9osgyIcw6o1avfDDDhH?utm_source=generator&theme=0'),
(22, 'Iris', 'Soft-Rock, Pop-Rock', 'Goo Goo Dolls', 1998, 'And I\'d give up forever to touch you\r\n\'Cause I know that you feel me somehow\r\nYou\'re the closest to Heaven that I\'ll ever be\r\nAnd I don\'t wanna go home right now\r\n\r\nAnd all I can taste is this moment\r\nAnd all I can breathe is your life\r\nAnd sooner or later, it\'s over\r\nI just don\'t wanna miss you tonight\r\n\r\nAnd I don\'t want the world to see me\r\n\'Cause I don\'t think that they\'d understand\r\nWhen everything\'s made to be broken\r\nI just want you to know who I am\r\n\r\nAnd you can\'t fight the tears that ain\'t coming\r\nOr the moment of truth in your lies\r\nWhen everything feels like the movies\r\nYeah, you bleed just to know you\'re alive\r\n\r\nAnd I don\'t want the world to see me\r\n\'Cause I don\'t think that they\'d understand\r\nWhen everything\'s made to be broken\r\nI just want you to know who I am\r\n\r\nAnd I don\'t want the world to see me\r\n\'Cause I don\'t think that they\'d understand\r\nWhen everything\'s made to be broken\r\nI just want you to know who I am\r\n\r\nAnd I don\'t want the world to see me\r\n\'Cause I don\'t think that they\'d understand\r\nWhen everything\'s made to be broken\r\nI just want you to know who I am\r\n\r\nI just want you to know who I am\r\nI just want you to know who I am\r\nI just want you to know who I am', 'https://images.genius.com/afef650b1e60e27d632e7c5765b39c37.1000x1000x1.png', 'https://youtube.com/embed/NdYWuo9OFAw?si=v7nSK3m_g5EJT9RU', 'https://open.spotify.com/embed/track/6Qyc6fS4DsZjB2mRW9DsQs?utm_source=generator&theme=0'),
(23, 'Ingat', 'Hip-Hop, Rap', 'Alyph', 2025, 'Kau kata kau nampak aku tengok dari jauh kau rasa terganggu\r\nAku kata aku tak berani mengejar apa yang aku mahu\r\nKau kata kau tak percaya aku boleh buat kau tunggu macam tu\r\nAku ingat masa aku jatuh cinta denganmu\r\n\r\nCam mana?\r\nDalam banyak orang aku dengannya?\r\nPenampilannya seindah bahasa\r\nKehadirannya memberi tenaga\r\n\r\nDamansara\r\nDinner dates\r\nMasuk cinema bawak take away\r\nMasa tu masa bersama lebih\r\nBerharga daripada harga duit\r\n\r\nMemandu lebuh raya ke arah utara\r\nDia nak bawak aku jumpa keluarga\r\nLeganya apabila aku di terima\r\nKalau ada jam pagi raya pun takpe\r\n\r\nAda banyak yang aku nak ceritakan\r\nAda banyak soalan dan perasaan\r\nHanya kau yang akan faham\r\nBoleh tak kita mula dari mula?\r\n\r\nKau kata kau nampak aku tengok dari jauh kau rasa terganggu\r\nAku kata aku tak berani mengejar apa yang aku mahu\r\nKau kata kau tak percaya aku boleh buat kau tunggu macam tu\r\nAku ingat masa aku jatuh cinta denganmu\r\n\r\nBeberapa tahun kemudian\r\nPabila kita mula mengejar impian\r\nAku mula sibuk dengan tugasan kerja\r\nSementara kau pula sibuk dengan uni final year\r\nBila kita bersama\r\nPerasaannya tak sama\r\nDulu senang tapi sekarang macam nak kena paksa\r\nTiba hari kita dua terima kenyataan\r\nBerputus, tu kali terakhir kita berdepan\r\n\r\nKau masih kelihatan seperti kali pertama kita bertemu\r\nKau telah buat keputusan yang baik dengan hidup yang baru\r\nWajah tiga-tiga Cahaya matamu serupa denganmu\r\nDia angguk dia setuju dan kata padaku\r\n\r\nAda banyak yang aku nak ceritakan\r\nAda banyak soalan dan perasaan\r\nHanya kau yang akan faham\r\nBoleh tak kita mula dari mula?\r\n\r\nKau kata kau nampak aku tengok dari jauh kau rasa terganggu\r\nAku kata aku tak berani mengejar apa yang aku mahu\r\nKau kata kau tak percaya aku boleh buat kau tunggu macam tu\r\nAku ingat masa aku jatuh cinta denganmu', 'https://dkg-is1.b-cdn.net/image/thumb/Music211/v4/d4/2d/e8/d42de8d8-8fa2-2c9a-fe0e-7c187b06c05b/24UM1IM32921.rgb.jpg/600x600bb.jpg', 'https://youtube.com/embed/_0kkOiTfUSY?si=wPCeW1Cc2e-TnBFd', 'https://open.spotify.com/embed/track/0QnyIDSjy366dQZjcHS2yF?utm_source=generator&theme=0'),
(24, 'Jane Doe', 'J-Pop, Jazz', 'Kenshi Yonezu and Hikari Utada', 2025, 'まるでこの世界で二人だけみたいだね\r\nなんて少しだけ夢をみてしまっただけ\r\n\r\nつま先に月明かり 花束の香り 指に触れる指\r\nさよなら もう行かなきゃ 何もかも忘れて\r\n\r\n硝子の上を裸足のまま歩く 痛むごとに血が流れて落ちていく\r\nお願い その赤い足跡を辿って 会いにきて\r\n\r\n錆びたプールに放たれていく金魚 靴箱の中隠した林檎\r\n萎びた君の肌に残る傷跡 犬のように泳いだ迷子\r\n\r\nどこにいるの (ここにいるよ) 何をしているの (ずっと見てるよ)\r\nこの世を間違いで満たそう\r\n側にいてよ\r\n遊びに行こうよ\r\nどこにいるの\r\n\r\n硝子の上を裸足のまま歩く 痛むごとに血が流れて落ちていく\r\nお願い その赤い足跡を辿って 会いにきて\r\n\r\nまるでこの世界で二人だけみたいだね\r\nなんて少しだけ夢をみてしまっただけ', 'https://images.genius.com/28e8b5e4393cc1f69b1c234ae5826c68.1000x1000x1.png', 'https://youtube.com/embed/sPLqsLsooJY?si=1U-El3CMbRh7uJoT', 'https://open.spotify.com/embed/track/4oE7MyJhqSD3BaHRpNs8Nl?utm_source=generator&theme=0'),
(25, 'Ku Akui', 'Pop', 'Hafiz Suip', 2012, 'Katakan padaku kekasih\r\nKesilapan yang pernah ku lakukan dulu\r\nTernyata aku yang harus di persalahkan\r\nKu akui\r\n\r\nAku leka dengan kerjayaku\r\nMengejar kekayaan di dunia ini\r\nBetapa hancurnya hatimu laluinya\r\nKu akui\r\n\r\nJika dapatku mengulangi\r\nPerjalanan cintaku bersamamu lagi\r\nAkan ku jaga\r\nSebaik baik cinta ini\r\n\r\nKini ku rasa kehilangan\r\nKu sedar betapa pentingnya kau di sisi\r\n\r\nYang selalu ada\r\nYang selalu rindu\r\nTerhadap diriku\r\n\r\nOh wo\r\nWowo oh\r\nJangan jangan\r\nJangan ku ulangi lagi\r\n\r\nJika dapatku mengulangi\r\nPerjalanan cintaku bersamamu lagi\r\nAkan ku jaga\r\nSebaik baik cinta ini wow\r\n\r\nKini ku rasa kehilangan\r\nKu sedar betapa pentingnya kau disisi\r\nYang selalu ada\r\nYang selalu rindu\r\nTerhadap diriku', 'https://images.genius.com/529516f7b16f6bd51ebf870ce8de4934.600x600x1.jpg', 'https://youtube.com/embed/VOkRVOkLvUo?si=vwalQsfF4SmpJDKr', 'https://open.spotify.com/embed/track/2oC99uEopMvVGjsb70kour?utm_source=generator&theme=0'),
(26, 'The World Is Ugly', 'Alternative-Rock, Emo', 'My Chemical Romance', 2012, 'These are the eyes and the lies of the taken\r\nThese are their hearts but their hearts don\'t beat like ours\r\nThey burn \'cause they are all afraid\r\nFor every one of us, there\'s an army of them\r\nBut you\'ll never fight alone\r\n\'Cause I wanted you to know\r\n\r\nThat the world is ugly\r\nBut you\'re beautiful to me\r\nWell are you thinking of me now (now)\r\n\r\nThese are the nights and the lights that we fade in\r\nThese are the words but the words aren\'t coming out\r\nThey burn \'cause they are hard to say\r\nFor every failing sun, there\'s a morning after\r\nThough I\'m empty when you go\r\nI just wanted you to know\r\n\r\nThat the world is ugly\r\nBut you\'re beautiful to me\r\nAre you thinking of me\r\nLike I\'m thinking of you\r\nI would say I\'m sorry, though\r\nThough I really need to go\r\nI just wanted you to know\r\n\r\nI wanted you to know\r\nI wanted you to know\r\nI\'m thinking of you every night, every day\r\n\r\nThese are the eyes and the lies of the taken\r\nThese are their hearts but their hearts don\'t beat like ours\r\nThey burn \'cause they are all afraid\r\nWhen mine beats twice as hard\r\n\r\n\'Cause the world is ugly\r\nBut you\'re beautiful to me\r\nAre you thinking of me\r\nLike I\'m thinking of you\r\nI would say I\'m sorry, though\r\nThough I really need to go\r\nI just wanted you to know\r\nThat the world is ugly (I just wanted you to know)\r\nBut you\'re beautiful to me (I just wanted you to know)\r\nAre you thinking of me\r\n\r\nStop your crying, helpless feeling\r\nDry your eyes and start believing\r\nThere\'s one thing they\'ll never take from you', 'https://images.genius.com/fefe6c98d8266a6386f93a27a65b8518.1000x1000x1.jpg', 'https://youtube.com/embed/Sfmzkj5QSto?list=RDSfmzkj5QSto', 'https://open.spotify.com/embed/track/6VtcgrVYo2xfygcWAfRpd1?utm_source=generator&theme=0');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
